import type { Metadata } from "next";

import "./globals.css";
import {Inter} from "next/font/google"
import Header from "./components/nav-bar";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased text-white bg-black`}>
   
            <div className="min-h-screen flex flex-col">
              <Header />
              <main className="flex-grow pt-16 md:pt-20">
                {children}
              </main>
            </div>
          
      </body>
    </html>
  );
}
